### ISSUE TITLE
About train-val_env.db and ../data/train

### ISSUE THREAD

**Issue by shanpufang** [anindox8/Machine-Learning-in-Dermatoscopy-Classification#2]
I’d appreciate it if you could give me these three files: train-val_env.db, ../data/train and ../data/val.
In addition, I wonder what are the formats of these three files?
Thanks very much!

**Comment by anindox8** [comment]
Hi @shanpufang. '../data/train' and '../data/val' were only directories containing subsets of the [publicly available ISIC 2019 dataset](https://challenge2019.isic-archive.com/), as described in the README. I would suggest downloading the dataset directly from the challenge site itself.

Over the course of model development, I would often store the variables computed in my current Jupyter notebook session into pickle called 'train-val_env.db' to save time on recomputing many of the same things again and again. So it's not really necessary and pertains only to my specific setup from one specific run of the notebook.

Hope this clarifies things better.
